### PR TITLE
Display progress-bar when adding new bill

### PR DESCRIPTION
**Pull request by thomaseizinger**
We use a linear progress-bar and deactivate both(!) buttons when adding
a new bill. This should prevent the user from accidentally clicking a
button again or aborting the process in-between.

Before: https://gyazo.com/750f6b29ca2376659b9c09e3a3058482
After: https://gyazo.com/fbbe10df5ae3933e248ce3389b9ad7b0

Related: #31.

### CODE REVIEW

**Comment by duffleit** [comment]
I don't like the usage of this horizontal progress bar, as we currently use the circular progress bar everywhere. Why don't we replace the button with a circular loading indicator?

**Comment by thomaseizinger** [comment]
I was thinking about that but the following things made me not do it:
1. It is somehow inconsistent that the cancel button is greyed out and the done button is replaced
2. The done-button is very small, therefore also the progress bar would be very small.
3. People might overlook the progress bar because they don't see the UI change in the moment the press the button because it is so small that it is completely covered by your thumb / finger.

However, I agree that it is slightly inconsistent because we use circular progress bars everywhere else. One thing to think about though would be to separate the usage of progress bars into loading and executing. We could use circular progress bars for loading and horizontal ones for actions that simply take long and change something. This mindset, however, would also require a change in the create-nobt wizard and I am not sure how the horizontal progress bar fits there.
After all, I am not to worried about this inconsistency.

**Comment by thomaseizinger** [comment]
This is what it would look like with a circular progress bar replacing the button:
https://gyazo.com/3e09a0ab373e385a817185b434224b5e

**Comment by KreMat** [comment]
I like the horizontal progress bar - is somehow a little bit more fancy

**Comment by duffleit** [comment]
I like the circular progress bar much more. In the horizontal solution, I do not like that the content moves when fading in.

**Comment by thomaseizinger** [comment]
I now opted for the circular progress bar and also disabled all inputs during the HTTP-request: https://gyazo.com/e2a0e41e9b6b483ff0cff40b67e59916

**Comment by thomaseizinger** [comment]
Just for further reference, I'd much rather merge the PRs myself. So if you don't have any more comments, just "accept" the review and I know that I can merge them anytime.

**Pull request merged**
