### PR TITLE
Feature/remove app bar custom styling

### PR DESCRIPTION
**Pull request by thomaseizinger**
Before reviewing this PR, it is best to read the following documentation page of react-toolbox: https://github.com/react-toolbox/react-toolbox/tree/master

After that, the changes should be pretty self-explanatory.

### CODE REVIEW

**Comment by duffleit** [comment]
This link does only point to tree/master? Which documentation do you mean?

**Comment by thomaseizinger** [comment]
I meant the README, sorry for not stating this more clearly. The important thing is that their main branch is 'dev' and not master, that is why I explicitly pointed to the master branch. The README contains all the relevant information though :)

**Comment by duffleit** [comment]
The title of the pull request is very missleading. The really interesting part is the introduction of the react-css-themr. Why didn't you style the appbar with `RTAppBar`?
Nevertheless I think we should bring this back to master asap, as this conecpt of styling changes a lot. At least for me and how i worked with react-toolbox till now. Thus, I've mereged it back.

**Comment by duffleit** [comment]
`src/layouts/AppLayout/AppLayout.js` on the master has changed. Thus, the build is broken. Please fix this and merge it back.

**Comment by thomaseizinger** [comment]
@duffleit The only customization was the font for the title. Styling it via the theme would have caused to also use this font for the AppBar in screens like BalanceOverview where we don't have the "nobt.io" text. That is why I considered a dedicated component to be the better choice: encapsulating the text "nobt.io" in combination with the style.
For example, I would like to reuse this component in the NobtLoader, as soon aa it is merged.

**Comment by thomaseizinger** [comment]
The PR kind of evolved over time. Initially I needed a custom theme for a component which then became obsolete again. However, I still considered it a good idea to build an initial structure for custom themes which is why I did not revert the changes.

**Comment by thomaseizinger** [comment]
Regarding the broken build: The theme-styles should never be referenced manually as they are included automatically during the build process.

**Pull request merged**
